version: '3'
services:
  codespace:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - test-network

  python-tests:
    image: python:3.9
    volumes:
      - ../python-project:/app
    working_dir: /app
    command: pytest --junitxml=results.xml -n auto # Parallel execution with pytest-xdist
    networks:
      - test-network

  java-tests:
    image: maven:3.8.5-openjdk-11
    volumes:
      - ../java-project:/app
    working_dir: /app
    command: mvn test -T 4 # Parallel execution with Maven
    networks:
      - test-network

  js-tests:
    image: node:16
    volumes:
      - ../js-project:/app
    working_dir: /app
    command: npm test -- --maxWorkers=4 # Parallel execution with Jest
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
